language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=1.9.5

before_install:
  - export DJANGO_SETTINGS_MODULE="rpi_csdt_community.settings"
  - export PYTHONPATH="/usr/local/lib/python2.7/dist-packages"
  - export PIP_USE_MIRRORS=true

install:
  - sudo $(type -P npm) install -g less
  - sudo $(type -P npm) install -g yuglify
  - sudo pip3 install setuptools --upgrade
  - sudo pip3 install --upgrade -r requirements.txt
  - sudo pip3 install coveralls
  
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python3 manage.py migrate
  - coverage run --source=rpi_csdt_community manage.py test

after_success:
  - pip3 freeze
  - echo Uploading code coverage data ...; coveralls